apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-catalog-deployment
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-catalog-deployment
  template:
    metadata:
      labels:
        app: backend-catalog-deployment
    spec:
      containers:
        - name: backend-catalog-deployment-container
          image: sujalsharma/backend-catalog-deployment:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-config
          volumeMounts:
            - name: backend-catalog-volume
              mountPath: /data # Path inside the container where the volume is mounted
      volumes:
        - name: backend-catalog-volume
          persistentVolumeClaim:
            claimName: ebs-claim-catalog