apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-account-deployment
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-account-deployment
  template:
    metadata:
      labels:
        app: backend-account-deployment
    spec:
      securityContext:
        runAsUser: 1000  # Run as non-root user
        fsGroup: 1000    # Set filesystem group
      containers:
        - name: backend-account-deployment-container
          image: sujalsharma/backend-account-deployment:v2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: DATABASE_URL_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: DATABASE_URL_ACCOUNT
          volumeMounts:
            - name: account-pv
              mountPath: /data/db
          resources:
            requests:
              memory: "64Mi"  # Minimum memory required
              cpu: "25m"     # Minimum CPU required
            limits:
              memory: "128Mi" # Maximum memory allowed
              cpu: "50m"     # Maximum CPU allowed
          livenessProbe:
            httpGet:
              path: /   # Health check endpoint
              port: 8080
            initialDelaySeconds: 30  # Wait 30 seconds before starting probes
            periodSeconds: 10        # Check every 10 seconds
          readinessProbe:
            httpGet:
              path: /    # Readiness check endpoint
              port: 8080
            initialDelaySeconds: 30  # Wait 30 seconds before starting probes
            periodSeconds: 10        # Check every 10 seconds
      volumes:
        - name: account-pv
          persistentVolumeClaim:
            claimName: account-pvc