apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-account-deployment
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-account-deployment
  template:
    metadata:
      labels:
        app: backend-account-deployment
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: backend-account-deployment-container
          image: sujalsharma/backend-account-deployment:v2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: DATABASE_URL_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: DATABASE_URL_ACCOUNT
          volumeMounts:
            - name: account-pv
              mountPath: / # Path inside the container where the volume is mounted
      volumes:
        - name: account-pv
          persistentVolumeClaim:
            claimName: account-pvc               
