apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-elasticsearch-statefulset
  namespace: ecommerce-app
spec:
  replicas: 2
  serviceName: "backend-elasticsearch-service"
  selector:
    matchLabels:
      app: backend-elasticsearch
  template:
    metadata:
      labels:
        app: backend-elasticsearch
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: backend-elasticsearch-volume
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: path.data
              value: "/usr/share/elasticsearch/data"
          volumeMounts:
            - name: backend-elasticsearch-volume
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: backend-elasticsearch-volume
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
