apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-elasticSearch-statefulset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-elasticSearch
  serviceName: "backend-elasticSearch-headless" # Required for StatefulSets
  template:
    metadata:
      labels:
        app: backend-elasticSearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
          ports:
            - containerPort: 80
              name: http
            - containerPort: 9300
              name: transport
          envFrom:
            - configMapRef:
                name: ecommerce-config
