apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-elasticsearch-statefulset
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-elasticsearch
  serviceName: "backend-elasticsearch-service"
  template:
    metadata:
      labels:
        app: backend-elasticsearch
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          envFrom:
            - configMapRef:
                name: ecommerce-config
          volumeMounts:
            - name: backend-elasticsearch-volume
              mountPath: /var/lib/elasticsearch/data
      volumes:
        - name: backend-elasticsearch-volume
          persistentVolumeClaim:
            claimName: elasticsearch-pvc