apiVersion: v1
kind: Service
metadata:
  name: backend-elasticsearch-service
spec:
  selector:
    app: backend-elasticsearch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 9300
      targetPort: 9300
  type: ClusterIP