apiVersion: v1
kind: Service
metadata:
  name: backend-graphql-service
spec:
  selector:
    app: backend-graphql-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer