apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-account-pvc
  namespace: ecommerce-app
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
