apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
  labels:
    type: ebs
    environment: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  awsElasticBlockStore:
    volumeID: vol-0abcd1234efgh5678  # Replace with your actual EBS volume ID
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1a  # Replace with your EBS volume's availability zone
