apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: ecommerce-app  # Match with PV namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Match with PV
  resources:
    requests:
      storage: 1Gi