apiVersion: v1
kind: PersistentVolume
metadata:
  name: account-pv
  namespace: ecommerce-app
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/account-db  # Unique path for each PV
  storageClassName: ""  # Match with PVC