# Secret for Database URLs
apiVersion: v1
kind: Secret
metadata:
  name: rds-secrets
  namespace: ecommerce-app
type: Opaque
data:
  DATABASE_URL_ACCOUNT: "cG9zdGdyZXMuYWNjb3VudHMuYmFja2VuZC5jb20="
  DATABASE_URL_ORDER: "cG9zdGdyZXMub3JkZXJzLmJhY2tlbmQuaW4="