# graphql-v2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-graphql-v2
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-graphql
      version: v2
  template:
    metadata:
      labels:
        app: backend-graphql
        version: v2
    spec:
      containers:
        - name: backend-graphql
          image: sujalsharma/backend-graphql-deployment:v2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-config
          volumeMounts:
            - name: backend-graphql-volume1
              mountPath: /data # Path inside the container where the volume is mounted
      volumes:
        - name: backend-graphql-volume
          persistentVolumeClaim:
            claimName: ebs-claim-graphql                