apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-account-deployment
  namespace: ecommerce-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1         
      maxUnavailable: 25%   
  selector:
    matchLabels:
      app: backend-account-deployment
  template:
    metadata:
      labels:
        app: backend-account-deployment
    spec:
      securityContext:
        runAsUser: 1000 
        fsGroup: 1000    
      containers:
        - name: backend-account-deployment-container
          image: sujalsharma/backend-account-deployment:3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: DATABASE_URL_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: DATABASE_URL_ACCOUNT
          volumeMounts:
            - name: account-pv
              mountPath: /data/db
          resources:
            requests:
              memory: "64Mi"  
              cpu: "25m"     
            limits:
              memory: "128Mi" 
              cpu: "50m"         
      volumes:
        - name: account-pv
          persistentVolumeClaim:
            claimName: catalog-pvc