apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-order-deployment
  namespace: ecommerce-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1         
      maxUnavailable: 25%   
  selector:
    matchLabels:
      app: backend-order-deployment
  template:
    metadata:
      labels:
        app: backend-order-deployment
    spec:
      securityContext:
        runAsUser: 1000 
        fsGroup: 1000   
      containers:
        - name: backend-order-deployment-container
          image: sujalsharma/backend-order-deployment:1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: DATABASE_URL_ORDER
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: DATABASE_URL_ORDER
          volumeMounts:
            - name: order-pv
              mountPath: /data/db
          resources:
            requests:
              memory: "64Mi"  
              cpu: "25m"     
            limits:
              memory: "128Mi" 
              cpu: "50m"          
      volumes:
        - name: order-pv
          persistentVolumeClaim:
            claimName: order-pvc